-- DROP TABLE IF EXISTS user;
-- DROP TABLE IF EXISTS product;

--DROP TABLE IF EXISTS COM_MSG;
CREATE TABLE IF NOT EXISTS COM_MSG (
    MSG_ID VARCHAR(20) NOT NULL,
    LANG_CD VARCHAR(2) NOT NULL,
    MSG_DESC VARCHAR(200) NOT NULL,
    GUID VARCHAR(50),
    MODIFIER_ID varchar(255) NULL,
    LAST_MODIFIED_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATER_ID varchar(255) NULL,
    CREATED_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MSG_ID, LANG_CD)
);

-- transaction control
CREATE TABLE IF NOT EXISTS COM_TR_CTRL (
    USE_YN VARCHAR(1) NOT NULL,
    TR_CTRL_CD VARCHAR(2) NOT NULL,
    TR_CTRL_OBJ_NM VARCHAR(20) NOT NULL,
    GUID VARCHAR(50),
    PRIMARY KEY (USE_YN, TR_CTRL_CD, TR_CTRL_OBJ_NM)
);